name: client deploy

on:
  push:
    paths:
      - 'client/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "xes-ethereum-extractor"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "client"